import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MilestoneMasterService, Milestone } from '../../services/milestone-master.service';

@Component({
  selector: 'app-milestone-master',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './mileston-master.html',
  styleUrls: ['./mileston-master.css']
})
export class MilestoneMasterComponent implements OnInit {
  milestones: Milestone[] = [];
  
  // Initialize with id: 0 (which acts as false in boolean checks)
  mileForm: Milestone = { id: 0, name: '', weightage: 0 };
  showMileForm = false;

  constructor(private milestoneService: MilestoneMasterService) {}

  ngOnInit() {
    this.loadMilestones();
  }

  loadMilestones() {
    this.milestoneService.getAll().subscribe({
      next: (data) => this.milestones = data,
      error: (err) => console.error('Error loading milestones', err)
    });
  }

  showAddForm() {
    // ID 0 means "New"
    this.mileForm = { id: 0, name: '', weightage: 0 };
    this.showMileForm = true;
  }

  handleMileSave() {
    if (!this.mileForm.name || this.mileForm.weightage <= 0) {
      alert('Please enter valid name and weightage');
      return;
    }

    if (this.mileForm.id && this.mileForm.id !== 0) {
      // --- UPDATE ---
      this.milestoneService.update(this.mileForm.id, this.mileForm).subscribe({
        next: () => {
          this.loadMilestones();
          this.cancelForm();
        },
        error: () => alert('Failed to update')
      });
    } else {
      // --- CREATE ---
      // We send the object; ID is generated by Backend
      this.milestoneService.create(this.mileForm).subscribe({
        next: () => {
          this.loadMilestones();
          this.cancelForm();
        },
        error: () => alert('Failed to create')
      });
    }
  }

  handleMileEdit(id: number) {
    const found = this.milestones.find(m => m.id === id);
    if (found) {
      // Create a copy to avoid editing the table row directly before saving
      this.mileForm = { ...found };
      this.showMileForm = true;
    }
  }

  handleMileDelete(id: number) {
    if (!confirm('Delete this milestone?')) return;
    
    this.milestoneService.delete(id).subscribe({
      next: () => this.loadMilestones(),
      error: () => alert('Failed to delete')
    });
  }

  cancelForm() {
    this.showMileForm = false;
    this.mileForm = { id: 0, name: '', weightage: 0 };
  }
}